name: clinified
description: Clinical Management System for Indian Healthcare
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Authentication & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Connectivity & Sync
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # FHIR Support
  fhir: ^0.0.1
  
  # ABDM Integration
  http: ^1.1.0
  
  # Payment Gateway
  razorpay_flutter: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 